### ISSUE TITLE
Breaks other mods that provide creative flight

### ISSUE THREAD

**Issue by FireEgl** [MasterGeneral156/CTD-Tweaks#2]
I can't use any items from other mods (like the Angel Ring from Extra Utilities 2) that give me creative flight when using CTD-Tweaks.

**Comment by MasterGeneral156** [comment]
Huh. That's gonna be a tricky one!

**Comment by MasterGeneral156** [comment]
Alright; I think this might be fixable with Baubles. Will let you know!

**Comment by MasterGeneral156** [comment]
Fixed in Build 1.5.5, now requires Baubles though!
